### ISSUE TITLE
highlighting tailwind class directives

### ISSUE THREAD

**Issue by shaynem** [pcbowers/alpine-intellisense#1]
First, I"m happy with seeing highlighting instead of a single color, so thank you for your work! 

It's fairly obvious why the below happens, but just pointing it out. 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/118681/173269353-717a7832-83d0-4974-8633-420a4dbe5810.png">

Possible to limit parsing to `x-*=` `@data-name=` `:data-name=` maybe?

I have a feeling the x- directive is being removed in future Alpine releases however.

**Comment by pcbowers** [comment]
@shaynem That's a good point! In reality, it's really not so much an issue with the grammar selection as it is with where the grammar is being injected. By changing the injection selector from `L:text.html` which allows the syntax to be injected anywhere to `L:meta.tag -meta.attribute` which only allows it to be injected within an HTML tag but not within the attribute itself, you get proper highlighting.

**Comment by pcbowers** [comment]
I just published a patch to the extension that implements this change. It should update automatically and fix this issue!

**Comment by Random72IsTaken** [comment]
It seems that it's still a problem for anything other than HTML files.
